Afin de pouvoir personnaliser votre classeur vous pouvez aller dans le menu **`File`** puis **`Make a copy...`**. Renommez le classeur.

# Découverte Python

## Premiers calculs

In [1]:
4+3

7

In [2]:
4 + 3 # les espaces entre opérandes et opérateurs sont optionnels

7

Le symbole `#` permet d'écrire des commentaires c'est-à-dire des lignes qui ne sont pas exécutées.

In [3]:
5+2*3 # La priorité des opérations est respectées

11

In [4]:
5**2 # Puissance

25

In [5]:
7/2 # La division 

3.5

L’opérateur `%` (appelé opérateur modulo) fournit le reste de la division entière d’un nombre par un autre.

In [6]:
7 % 2

1

## Premiers scripts

Nous allons commencer à rédiger des petits programmes Python. L'intérêt de ces petits scripts est de vous familiariser avec le langage Python.  

Quand vous exécutez un programme, vous verrez aussi une sortie. L'exemple de code ci-dessus contient une seule commande print("Bonjour!") qui produit une seule ligne de sortie.
Appuyez sur <B>Shift Entrée</B> dans la ligne <I>In [x]</I> pour valider le contenu du champ de saisie.

In [7]:
print("Bonjour, Python !")

Bonjour, Python !


Quelques explications sur ce 1er script:
<UL>
<LI><B>print</B> est le nom de la commande Python qui envoie des messages vers la sortie.
<LI>Les parenthèses () après la commande print sont utilisées pour contenir ce que vous voulez afficher.
<LI>Les guillemets " " sont utilisés pour contenir le texte Bonjour! à l'intérieur. Sans les guillemets, Python penserait que Bonjour est censé être une commande. Cela entraînerait une erreur puisque cette commande n'existe pas.
</UL>
Essayez maintenant:

In [8]:
print(Bonjour!)

SyntaxError: invalid syntax (<ipython-input-8-384e2b9fd22c>, line 1)

Une erreur est indiquée; une mauvaise commande a été donnée, ce qui génère une erreur et le force à s'arrêter.

### Les variables

Les variables permettent de stocker des valeurs. Chaque variable a un nom ; un exemple de nom de variable que nous utiliserons est <B>Nb</B>. Pour stocker de l'information dans une variable, nous écrivons une commande en utilisant le signe égal (=). On dit également que l'on affecte une valeur à la variable Nb.

In [9]:
Nb = 13
print(Nb+1)

14


L'instruction très utile "a=a+1" est très utile en programmation : 

In [10]:
a=3
a=a+1
print(a)
print(A) # la casse (distinction entre majuscules et minuscules) est prise en compte

4


NameError: name 'A' is not defined

En première ligne, la valeur 3 est affectée dans la place mémoire "a". 
En deuxième ligne, l'ordinateut calcule "a+1" puis l'affecte dans la place mémoire "a" : la variable "a" devient donc égale à 4. On a incrémenté la variable "a" d'une unité. 
La dernière ligne confirme le fait que le langage machine différencie les lettres minuscules et majuscules, d'où le message d'erreur.

In [11]:
a=5
b=3
b=2*b-a
print("La valeur de b est",b)

La valeur de b est 1


### Les différents types de variable

Les variables peuvent contenir différents types d'informations. On dit qu'elles sont de type :
- *int* : entiers (ex : -2 ; 5)
- *float* : décimal (ex -2.0 ; 2e6=2000000.0)
- *str* : chaîne de caractère (ex 'Bonjour' ; "Autre exemple" ; "2+3" ; "5")
- *bool* : Booléen : Vrai ou Faux. (ex : 2==3, False, 3<4)
- *list* : Tableau ou liste (ex : [1,'toto', 2.0] ; [[1,2],[3,4]])

In [12]:
chaine="Je suis une chaîne de caractère"
type(chaine)

str

Vous n'avez pas besoin d'indiquer le type des variables. 
On peut changer de type en cours de route (attention cela n'est pas recommandé).

In [ ]:
a="Je suis une chaîne"
print(a)
a=12 # et maintenenant je suis un nombre !!!
print(a)

### Affectations simultanées

In [ ]:
x,y=1,2
print(x,y)

### Instruction Saisir

Avant d'entammer les boucles et les différents algorithmes, nous allons découvrir comment sous Python on réalise la saisie interactive d'une valeur dans une variable.

In [ ]:
x=eval(input("Saisir la valeur de x : "))
print("vous avez saisi la valeur",x)

In [ ]:
x = int(input("Donnez un entier : "))

Par défaut, la fonction *input()* renvoie une chaîne de caractères. Il faut donc utiliser la fonction *int()* qui permet d’obtenir un entier ou la fonction *eval()*.

### Boucle *for*

La syntaxe de la boucle *for* est un peu particulière : On dit à une variable de parcourir un certain intervalle de valeurs. Cet intervalle peut être décrit par exemple par l'instruction `range(n)`. Voici quelques exmples:

In [ ]:
for i in range(5):
    print("je répète 5 fois la même chose. Ici, i=",i)

Ce qu'il faut retenir c'est :
- que la boucle `for i in range(n)` tournera `n` fois
- que la variable `i` prendra les valeurs entières entre 0 et `n-1`

**Importance du symbole**`:`
Remarquez bien le `:` après le range. Cela marque le début d'un *bloc*.

Un *bloc* en python se distingue par le ***décalage par rapport à la marge***. Il permet de délimiter le début et la fin du contenu de la boucle *for*. En effet, contrairement à Matlab, il n'y a par de mot clé `end` pour signifier la fin de la boucle pour.

On retrouvera cette notion de bloc également pour les boucles tant que, les tests si... alors... sinon..., les définitions de fonction etc...

Soyez donc très attentif à la présence des `:` et au décalage de marge.

 #### Fonction range()

In [27]:
range(10)

range(0, 10)

Si on souhaite afficher les valeurs, il est nécessaire de convertir le résultat en liste grâce à la fonction *list()*:

In [28]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [29]:
list(range(5, 10))

[5, 6, 7, 8, 9]

In [ ]:
list(range(0, 10, 3))

De manière générale, on a :

range(valeur_initiale, borne_de_fin, pas)

Le pas peut être positif ou négatif. La valeur de la borne de fin (maximale ou minimale) n’est pas atteinte.

Pour parcourir les indices d’une liste, il est possible de combiner range() et len() comme ci-dessous :

In [ ]:
c = ["Marc", "est", "dans", "le", "jardin"]
for i in range(len(c)):
    print("i vaut", i, "et c[i] vaut", c[i])

### Boucle *while*

Exécuter le programme ci-dessous. Quel est son rôle ?
Remarquez la présence des `:` et le décalage de marge.

In [ ]:
x=0
while (x==0):
       x=eval(input("saisissez un nombre non nul : "))
print("l'inverse de",x,"est",1/x)

Le programme ...

### Instruction *if...else*

Observez le fonctionnement du programme ci-dessous :

In [ ]:
n=eval(input("Saisissez la valeur de n"))
if n%2==0 :
    print(n, " est un nombre pair")
else : 
    print(n, " est un nombre impair")

Pour tester l'égalité, on utilise l'opérateur `==`; Le signe `=` étant réservé pour l'affectation d'une valeur à une variable.

## Les fonctions

Pour créer une fonction sous Python, on utilise le mot clé *def*.

In [ ]:
def f(x):
    y=3*x-2
    return y

print(f(2))

Ici nous avons défini une fonction (au sens mathématiques).

On reconnaît le mot clé *def*. On le fait suivre du nom de la fonction - ici f - suivi par les arguments que cette fonction prend en entrée entre parenthèse - ici un seul argument est passé : x.
Pour savoir ou commence et ou finit la fonction, python utilise la notion de bloc. Un bloc commence par `:` et est décalé par rapport au début de la marge Ainsi notre fonction commence à la ligne `y=` et se finit après le `return`.
La ligne *return y* est importante : c'est elle qui indique ce que renvoie la fonction.

In [ ]:
f(5)

La fonction *f* est ici un moyen rapide d'exécuter le calcul `y=3*x-2` sans avoir à retaper la formule.

### Généralisation de la notion de fonction

Une fonction en programmation correspond à un morceau de code auquel on peut faire appel par un nom.
- Une fonction peut prendre un ou plusieurs arguments en entrée.
- Une fonction ne retourne pas forcément de valeur. Elle effectue une tâche précise.
- Une fonction permet de rendre le code plus facile à lire en séparant un problème complexe en plusieurs tâches plus simples pouvant être traitées séparément.
- Une fonction permet également d'être utilisée dans plusieurs programmes 'principaux'.

In [ ]:
def table(n,limite):
    print("Table de multiplication de ",n)
    for i in range(1,limite+1):
        print(i,"x",n,"=",i*n)

Testez cette fonction.

Il est fortement conseillé d'utiliser des fonctions dans les programmes (projets) afin de les rendre plus lisibles. Avant de se lancer dans l'écriture d'unprogramme, il est important de réfléchir aux différentes tâches que l'on souhaite réaliser, de définir les parties qui seront rédigées sous la forme de fonction et de préciser clairement les variables d'netrée et de sortie des fonctions.
Il est également important de donner des noms claires et explicites aux fonctions en faisant également attention à ce que les noms ne soient pas déjà pris par Python (et les librairies utilisées).

## Les types de données

Il existe différents types de données:
- Le type int (entier)
- Le type float (flottant)
- Le type str (chaînes de caractères)
- Le type bool (booléen)
- Le type list (liste)
- Le type complexe (complex)

Pour connaître le type d’une donnée ou le type de la valeur d’une variable, il suffit d’utiliser la fonction *type()*.

In [ ]:
b = 1 + j

Ici message d'erreur

In [ ]:
b = 1 + 1j

## Les listes

In [ ]:
a = list(range(1,10,2))
a[0]

In [ ]:
a = list(range(7,10))
len(a) # permet d'obtenir la longueure (taille) d'une liste

# Introduction NumPy

Cette partie a été rédigée à partir du site : https://courspython.com/apprendre-numpy.html.

La bibliothèque ***NumPy*** (http://www.numpy.org/) permet d’effectuer des calculs numériques avec Python. Elle introduit une gestion facilitée des tableaux de nombres.

Il faut au départ importer le package numpy avec l’instruction suivante :

In [1]:
import numpy as np

NumPy définit par défaut la valeur de pi.

In [2]:
np.pi

3.141592653589793

## Tableaux - *numpy.array()*

On crée les tableaux à partir de la fonction *numpy.array()*

In [3]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a   # permet de visualiser le tableau
type(a) # permet de connaitre le type; ici numpy.ndarray

numpy.ndarray

Pour accéder à des éléments du tableau, on spécifie l'indice de la ligne (1ère dimension) et l'indice de la colonne (2ème dimension)  

In [4]:
a[0,2]

3

Attention: les indices commencent à 0 !

### La fonction *numpy.arange()*

In [5]:
m = np.arange(3, 15, 2)
m

array([ 3,  5,  7,  9, 11, 13])

Noter la différence entre *numpy.arange()* et *range()* :
*numpy.arange()* retourne un objet de type numpy.ndarray.
*range()* retourne un objet de type range.

In [6]:
np.arange(0, 11*np.pi, np.pi)  # np.arange accepte en arguments d'entrée des nombres non entiers

array([ 0.        ,  3.14159265,  6.28318531,  9.42477796, 12.56637061,
       15.70796327, 18.84955592, 21.99114858, 25.13274123, 28.27433388,
       31.41592654])

### La fonction *numpy.linspace()*

*numpy.linspace()* permet d’obtenir un tableau 1D allant d’une valeur de départ à une valeur de fin avec un nombre donné d’éléments.

In [7]:
np.linspace(3, 9, 10)

array([3.        , 3.66666667, 4.33333333, 5.        , 5.66666667,
       6.33333333, 7.        , 7.66666667, 8.33333333, 9.        ])

## Tableau et slicing

Lors de la manipulation de tableaux, on a souvent besoin de récupérer une partie d’un tableau. Pour cela, Python permet d’extraire des tranches d’un tableau grâce au "slicing" (tranchage, en français); on indique entre crochets des indices pour définir le début et la fin de la tranche et à les séparer par deux-points `:`.

### Tableau 1D

In [8]:
a = np.array([12, 25, 34, 56, 87])
a[1:3]

array([25, 34])

In [9]:
a[1:]

array([25, 34, 56, 87])

In [10]:
a[:3]

array([12, 25, 34])

In [11]:
a[:]

array([12, 25, 34, 56, 87])

### Tableau 2D

In [12]:
a = np.array([[1, 2, 3],
               [4, 5, 6]])
a[0,1]

2

In [13]:
a[:,1:3]

array([[2, 3],
       [5, 6]])

In [14]:
a[0,:]

array([1, 2, 3])

### Tableaux "remarquables"

In [15]:
np.zeros(3)

array([0., 0., 0.])

np.zeros(n,m) retourne un tableau contenant des zéros de taille n x m

In [16]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.ones((2,1))

array([[1.],
       [1.]])

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Changement de la taille d'un tableau

In [19]:
a = np.arange(1, 6)
a

array([1, 2, 3, 4, 5])

In [20]:
a.shape = (1, np.size(a))
a

array([[1, 2, 3, 4, 5]])

In [21]:
a.shape = (np.size(a), 1)
a

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [22]:
u = np.arange(1, 16)
u

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [23]:
np.shape(u)

(15,)

In [24]:
u.shape = (3, 5)
u

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [25]:
np.shape(u)

(3, 5)

## Fonction et tableaux

In [ ]:
x = np.linspace(-np.pi/2, np.pi/2, 3)
x
y = np.sin(x)
y

NumPy dispose d’un grand nombre de fonctions mathématiques qui peuvent être appliquées directement à un tableau. 
Dans ce cas, la fonction est appliquée à chacun des éléments du tableau.

## Fonctions mathématiques

| Python           |                            |
|---               |---                         |
|x** n             |x à la puissance n          |
|numpy.sqrt(x)     |racince carrée              |
|numpy.exp(x)      |fonction exponentielle      |
|numpy.log(x)      |fonction logarithme népérien|
|numpy.abs(x)      |fonction valeur absolue     |

### Quelques fonctions pour les nombres complexes

| Python           |                            |
|---               |---                         |
|numpy.real(x)     |partie réelle               |
|numpy.imag(x)     |partie imaginaire           |
|numpy.abs(x)      |module                      |
|numpy.angle(x)    |phase                       |
|numpy.conj(x)     |conjugué                    |

### Les arrondis

| Python           |                                     |
|---               |---                                  |
|numpy.around(x,n) |arrondi à n décimales                |
|numpy.trunc(x)    |retourne la partie entière du nombre |

## Nombres aléatoires

La fonction *numpy.random.random()* permet d’obtenir des nombres compris entre 0 et 1 par tirage aléatoire avec une loi uniforme. Il faut noter que ces nombres aléatoires sont générés par un algorithme et ils ne sont donc pas vraiment « aléatoires » mais pseudo-aléatoires.

In [ ]:
np.random.random()

In [ ]:
np.random.random(3)

In [ ]:
np.random.random((2,3))

# Tracé de courbes 

Pour tracer des courbes, la solution la plus simple est l'utilisation de la bibliothèque ***matplotlib***. Penser à regarder le site: https://www.tutorialspoint.com/matplotlib/index.htm si vous souhaitez faire d'autres tracés que ceux illustrés ci-dessous.

## *plot()*

L’instruction *plot()* permet de tracer des courbes qui relient des points dont les abscisses et ordonnées sont fournies dans des tableaux. On donne ci-dessous plusieurs exemples pour tracer des courbes.

### Exemple 1

In [26]:
import numpy as np
import matplotlib.pyplot as plt

x = np.array([1, 3, 4, 6])
y = np.array([2, 3, 5, 1])
plt.plot(x, y)

plt.show() # affiche la figure a l'ecran

ModuleNotFoundError: No module named 'matplotlib'

### Exemple 2

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(0, 2*np.pi, 30)
y = np.cos(x)
plt.plot(x, y)

plt.show() # affiche la figure a l'ecran

### Exemple 3 : limites des axes

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(0, 2*np.pi, 30)
y = np.cos(x)
plt.plot(x, y)
plt.xlim(-1, 5)

plt.show()

### Exemple 4

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(0, 2*np.pi, 30)
y = np.cos(x)
plt.plot(x, y)
plt.xlim(0, 2*np.pi)
plt.ylim(-2, 2)
plt.title("Fonction cosinus")
plt.xlabel("abscisses")
plt.ylabel("ordonnees")
plt.show()

### Exemple 5 : affichage de plusieurs courbes avec une légende

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(0, 2*np.pi, 30)
y1 = np.cos(x)
y2 = np.sin(x)
plt.plot(x, y1, "r--", label="cos(x)")
plt.plot(x, y2, "b:o", label="sin(x)")
plt.legend()
plt.title("Fonctions cosinus et sinus")
plt.xlabel("abscisses")
plt.ylabel("ordonnees")
plt.show()

### Exemple 6

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(0, 2*np.pi, 20)
y = np.sin(x)
plt.plot(x, y, "o-", label="ligne -")
plt.plot(x, y-0.5, "o--", label="ligne --")
plt.plot(x, y-1, "o:", label="ligne :")
plt.plot(x, y-1.5, "o-.", label="ligne -.")
plt.plot(x, y-2, "o", label="pas de ligne")
plt.legend()

plt.show()

## *bar()*

In [ ]:
import matplotlib.pyplot as plt
langs = ['C++', 'Java', 'Python']
students = [23,35,12]
plt.bar(langs,students)
plt.show()

Les exemples ci-dessous sont extraits de https://benalexkeen.com/bar-charts-in-matplotlib/

In [ ]:
import matplotlib.pyplot as plt
plt.style.use('ggplot')

x = ['Nuclear', 'Hydro', 'Gas', 'Oil', 'Coal', 'Biofuel']
energy = [5, 6, 15, 22, 24, 8]

x_pos = [i for i, _ in enumerate(x)]

plt.bar(x_pos, energy, color='green')
plt.xlabel("Energy Source")
plt.ylabel("Energy Output (GJ)")
plt.title("Energy output from various fuel sources")

plt.xticks(x_pos, x)

plt.show()

In [ ]:
x = ['Nuclear', 'Hydro', 'Gas', 'Oil', 'Coal', 'Biofuel']
energy = [5, 6, 15, 22, 24, 8]
variance = [1, 2, 7, 4, 2, 3]

x_pos = [i for i, _ in enumerate(x)]

plt.bar(x_pos, energy, color='green', yerr=variance)
plt.xlabel("Energy Source")
plt.ylabel("Energy Output (GJ)")
plt.title("Energy output from various fuel sources")

plt.xticks(x_pos, x)

plt.show()

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
N = 5
men_means = (20, 35, 30, 35, 27)
women_means = (25, 32, 34, 20, 25)

ind = np.arange(N) 
width = 0.35       
plt.bar(ind, men_means, width, label='Men')
plt.bar(ind + width, women_means, width,
    label='Women')

plt.ylabel('Scores')
plt.title('Scores by group and gender')

plt.xticks(ind + width / 2, ('G1', 'G2', 'G3', 'G4', 'G5'))
plt.legend(loc='best')
plt.show()


### *scatter()*

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

plt.style.use('ggplot')

x = np.random.rand(100) * 10
y = x * np.random.rand(100) * 5
plt.scatter(x, y)
plt.plot()

# Calculs matriciels 

## Produit matriciel

Le produit d'une matrice n x m par une matrice m x p donne en résultat une matrice de taille n x p. On utilise l'opérateur np.dot 

In [ ]:
a = np.array([[1, 2, 3],[4, 5, 6]])
b = np.array([[4],
              [2],
              [1]])
np.dot(a,b)

## Produit terme à terme

Il est possible de réaliser un produit terme à terme grâce à l’opérateur `*`. Il faut dans ce cas que les deux tableaux aient la même taille. Attention car cette opération ne correspond pas au produit matriciel!

In [ ]:
a = np.array([[1, 2, 3],
                  [4, 5, 6]])
b = np.array([[2, 1, 3],
                  [3, 2, 1]])
a*b

 ## Inversion d'une matrice

In [ ]:
from numpy.linalg import inv
a = np.array([[1, 3, 3],
                  [1, 4, 3],
                  [1, 3, 4]])
inv(a)
np.dot(a,inv(a))

## Vecteurs et valeurs propres

In [ ]:
from numpy.linalg import eig
A = np.array([[ 1, 1, -2 ], [-1, 2, 1], [0, 1, -1]])
D, V = eig(A)

In [ ]:
D, V

V contient en colonne les vecteurs propres de A et D contient les valeurs propres associées. 